# تمرین اول

در این بخش اومدیم و کتابخونه های مد نظر رو فراخوانی کردیم

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import SGDRegressor

## (بخش الف)

سپس دیتاست مربوطه رو با تابع پانداز خوندیم و ستون هاشو برای راحتی کار باهاش تبدیل به عدد کردیم

In [12]:
raw_data = pd.read_excel("./CSM_dataset.xlsx", na_values="NaN").set_axis(labels=list(range(14)), axis=1)
raw_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,13 Sins,2014,6.3,8,9130,4000000.0,45.0,1,0,3280543,4632,425,636,1120000.0
1,22 Jump Street,2014,7.1,1,192000000,50000000.0,3306.0,2,2,583289,3465,61,186,12350000.0
2,3 Days to Kill,2014,6.2,1,30700000,28000000.0,2872.0,1,0,304861,328,34,47,483000.0
3,300: Rise of an Empire,2014,6.3,1,106000000,110000000.0,3470.0,2,0,452917,2429,132,590,568000.0
4,A Haunted House 2,2014,4.7,8,17300000,3500000.0,2310.0,2,0,3145573,12163,610,1082,1923800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Child 44,2015,6.4,4,1210000,50000000.0,66.0,1,4,3701061,9325,641,1859,NaN
227,Aloha,2015,5.5,15,21000000,37000000.0,2815.0,1,13,7119456,18803,1128,2290,NaN
228,Unfinished Business,2015,5.4,8,10200000,35000000.0,2777.0,1,7,3450614,6823,325,409,NaN
229,War Room,2015,5.4,1,12300000,3000000.0,NaN,1,10,66872,400,67,201,NaN
230,The Gallows,2015,4.4,15,22600000,100000.0,2720.0,1,-5,659772,2841,431,606,NaN

## (بخش ب)

برای اینکه بدونیم داده گم شده داریم یا نه،تعداد داده های گم شده هر بخش رو نمایش میدیم

In [13]:
print(raw_data.isna().sum())

0      0
1      0
2      0
3      0
4      0
5      1
6     10
7      0
8      0
9      0
10     0
11     0
12     0
13    35
dtype: int64

طبق خروجی بالا در ستون های 5و 6و 13 داده گم شده داشتیم.<br>
چون این ستون ها داده هاش ترتیبی ان، داده های گم شده این ستون ها رو با میانگین اونها پر میکنیم.<br>
در نهایت هم کد باکس قبلی رو میزنیم که مطمئن شیم داده های گم شده الان با مقداری که میخواستیم پر شدن.

In [14]:
mis_col = [5, 6, 13]
for col in range(14):
    if col in mis_col:
        _mean = raw_data[col].mean()
        raw_data[col] = raw_data[col].fillna(_mean)

print(raw_data.isna().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
dtype: int64

حالا باید نرمال سازی رو انجام بدیم.
برای ستون هایی که داده های آنها ترتیبی است نرمال سازی رو انجام میدیم و در آخر دیتاست رو نمایش میدیم

In [15]:
cont_attr = [1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
min_max_scaler = MinMaxScaler()
x = raw_data[cont_attr].values
x_scaled = min_max_scaler.fit_transform(x)

normalized = pd.DataFrame(x_scaled, columns=cont_attr, index=raw_data.index)
raw_data[cont_attr] = normalized
raw_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,13 Sins,0.0,0.571429,8,0.000010,0.015724,0.009949,0.000000,0.567164,0.100528,0.012498,0.030444,0.016578,0.036061
1,22 Jump Street,0.0,0.714286,1,0.298598,0.199776,0.764461,0.166667,0.597015,0.017857,0.009348,0.004370,0.004848,0.397981
2,3 Days to Kill,0.0,0.553571,1,0.047741,0.111751,0.664044,0.000000,0.567164,0.009323,0.000882,0.002436,0.001225,0.015532
3,300: Rise of an Empire,0.0,0.571429,1,0.164849,0.439843,0.802406,0.166667,0.567164,0.013861,0.006552,0.009456,0.015379,0.018271
4,A Haunted House 2,0.0,0.285714,8,0.026901,0.013724,0.534012,0.166667,0.567164,0.096391,0.032821,0.043696,0.028204,0.061966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Child 44,1.0,0.589286,4,0.001878,0.199776,0.014808,0.000000,0.626866,0.113417,0.025163,0.045917,0.048458,0.097880
227,Aloha,1.0,0.428571,15,0.032656,0.147761,0.650856,0.000000,0.761194,0.218192,0.050741,0.080802,0.059693,0.097880
228,Unfinished Business,1.0,0.410714,8,0.015859,0.139759,0.642064,0.000000,0.671642,0.105741,0.018410,0.023281,0.010661,0.097880
229,War Room,1.0,0.410714,1,0.019125,0.011723,0.510700,0.000000,0.716418,0.002028,0.001077,0.004799,0.005239,0.097880
230,The Gallows,1.0,0.232143,15,0.035144,0.000120,0.628876,0.000000,0.492537,0.020201,0.007664,0.030874,0.015796,0.097880

ستون 3 برای نمایش ژانر فیلم است و نرمال سازی این ستون اشتباهه چون ترتیب داده ها برای ما مهم نیس.برای همین به روش وان هت این کار را انجام میدهیم

In [16]:
col_name = raw_data.columns[3]
raw_data[col_name] = raw_data[col_name].astype(str)

X = pd.get_dummies(raw_data, columns=[col_name], dtype=int)

حالا ستون 0 را که اسم داده ها درون اون است به طور کامل پاک میکنیم

In [17]:
col_to_drop = X.columns[0]
X = X.drop(columns=[col_to_drop])
X

,1,2,4,5,6,7,8,9,10,11,...,3_10,3_12,3_15,3_2,3_3,3_4,3_6,3_7,3_8,3_9
0,0.0,0.571429,0.000010,0.015724,0.009949,0.000000,0.567164,0.100528,0.012498,0.030444,...,0,0,0,0,0,0,0,0,1,0
1,0.0,0.714286,0.298598,0.199776,0.764461,0.166667,0.597015,0.017857,0.009348,0.004370,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.553571,0.047741,0.111751,0.664044,0.000000,0.567164,0.009323,0.000882,0.002436,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.571429,0.164849,0.439843,0.802406,0.166667,0.567164,0.013861,0.006552,0.009456,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.285714,0.026901,0.013724,0.534012,0.166667,0.567164,0.096391,0.032821,0.043696,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,1.0,0.589286,0.001878,0.199776,0.014808,0.000000,0.626866,0.113417,0.025163,0.045917,...,0,0,0,0,0,1,0,0,0,0
227,1.0,0.428571,0.032656,0.147761,0.650856,0.000000,0.761194,0.218192,0.050741,0.080802,...,0,0,1,0,0,0,0,0,0,0
228,1.0,0.410714,0.015859,0.139759,0.642064,0.000000,0.671642,0.105741,0.018410,0.023281,...,0,0,0,0,0,0,0,0,1,0
229,1.0,0.410714,0.019125,0.011723,0.510700,0.000000,0.716418,0.002028,0.001077,0.004799,...,0,0,0,0,0,0,0,0,0,0
230,1.0,0.232143,0.035144,0.000120,0.628876,0.000000,0.492537,0.020201,0.007664,0.030874,...,0,0,1,0,0,0,0,0,0,0

داده ها را به آرایه تبدیل میکنیم که کار با اونها آسون تر بشه و سپس ستون 4 که میخواهیم روی اون رگرسیون را حساب کنیم جدا میکنیم.<br>
سپس داده ها رو به صورت 80 و 20 به داده آموزش و داده تست تبدیل میکنیم

In [18]:
Y = np.array(X.pop(4))
X = np.array(X)
print(X.shape, Y.shape)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
print(X_test.shape, Y_test.shape)

(231, 22) (231,)
(47, 22) (47,)

## (بخش ج)

حالا رگرسیونی مبتنی بر نزول در راستای گرادیان برای تخمین ستون گراس آموزش میدهیم و اسکور اون رو نمایش میدهیم که ببینیم درصد تشبیه ما چقدر بوده.<br>
در اینجا 52 درصد داده ها رو توانسته درست پیش بینی کنه که درصد نسبتا خوبیه برا داده های پیوسته ما .

In [19]:
sgd_reg = SGDRegressor(max_iter=500000, tol=0.00000001)
sgd_reg.fit(X_train, Y_train)
score = sgd_reg.score(X_test, Y_test)
print(score, sgd_reg.n_iter_)

0.564514402969233 654

## (بخش د)

در نهایت هم میانگین مربع خطا رو حساب میکنیم که میبینیم مقدار خیلی کمی داره(0.005) که مقدار خیلی خوبیه برای مدل ما

In [20]:
y_pred = sgd_reg.predict(X_test)
mse = np.mean((Y_test - y_pred) ** 2)
print(mse)

0.008719421192861478

## (بخش ه)

### توضیحات بخش ه:
دلایل حذف ستون 0:<br>شناسه یکتا : نام فیلم فقط یک برچسب متنی و هویتی است و هیچ رابطه ریاضی یا عددی با میزان فروش یا گراس ندارد.
جلوگیری از بیش‌برازش : اگر تبدیل به عدد شود، ابعاد داده به شدت بالا رفته و مدل به جای یادگیری الگوهای کلی، فقط نام‌ها را حفظ می‌کند.